apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: helloworld
  namespace: helloworld
spec:
  port:
    targetPort: helloworld
  to:
    kind: Service
    name: helloworld
    weight: 100
  tls:
    termination: edge
