apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-secret
  namespace: helloworld
spec:
  encryptedData:
    foo: AgB8zOPOTDJ9wnLewX7INM6Ezj+uuOOH1a+YBTpWpt+emdOuoKbkyKaKdY+PGMFO60EHAV4PPqYeZ8znnQLBSP0fMfDYYBrIRiNavs1T4g2QgXu3uYwSQiLmF5EmYk6rckhg+0JuyiXAKi520QZ8+rrGLvbSu0SsyogTcw+dhjd3qkgEGH1ETizD65sySXadQHP0o9aYm2WiAl/Z8aEtcMlSbu0+MhJYqvlAufqkX/hZezybQzee8wLkVNfu39dVU6xGH1Nex6sj9qae++Zc4nMauRrGr3hQrcnZyaieukSQiGE8OWOH5Sxi5MsRMs0S9vU8vXKvB4dRkRFAy0H5EpzyOYBj1QnlZMjduw12J8AXqrGNlgD9L5VAIDNIhKEhbFJ1DkY/YVHtIY0sYkwb9PeY6fAfvjWPCwYxuMn7592Uq4pIue59qRVNdyjC3MH3weuH62s7rDluawNYKySIBD52ulh9Cg5hQPxJZ2Pr0G2S7QTlqdFlUFNqOspDI9/ro645C3xtt3XaXfs4VaTDt59Uca2+wbeXxieri29sPO6vLiga5EW3Kp8nZz3nF5wmAqVYkjoNeqmWFBeVthCGnTEm1lrd+vQbp+JFn/Qn1T4Gg6jAMUqngKyc7JByEzvCw6YIEM9V7vZqyDXwX7JneN2U47Eg6iLc8nXpsDix50voPvkkHXyC/KK+QXwMsXyIAQZ2Smw=

