apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: helloworld
  namespace: helloworld
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: helloworld
  targetCPUUtilizationPercentage: 80