apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  type: ClusterIP
  ports:
    - name: helloworld
      port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    name: helloworld
