apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  namespace: helloworld
spec:
  minReadySeconds: 5
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: helloworld
        image: luisbarrueco/flux-example:v0.0.1
        args:
        - -msg=Hello, world
        ports:
        - containerPort: 8081
      - name: sidecar
        image: quay.io/weaveworks/sidecar:master-a000001
        args:
        - -addr=:8080
        ports:
        - containerPort: 8080
